# Generated by Django 2.2.2 on 2019-06-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressureV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millis', models.IntegerField()),
                ('pressure', models.IntegerField()),
            ],
        ),
    ]
