# Generated by Django 2.2.2 on 2019-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurev2',
            name='millis',
            field=models.BigIntegerField(),
        ),
    ]
